import Head from 'next/head';
import React, { useState, useEffect } from 'react';

import {
  Box,
  Heading,
} from '@chakra-ui/react';
import { createAlchemyWeb3 } from '@alch/alchemy-web3';

import components from '../components';
import txConstants from '../constants';
import styles from '../styles/Home.module.css';
import { toGwei } from '../utils/math';

// import { Parallax, ParallaxLayer, IParallax } from '@react-spring/parallax';
// import GraphView from './graph';

const { TX_LIMIT } = txConstants;
const {
  ListView,
  Subscription,
  StatisticPanel,
} = components;

export default function Home() {
  // const parallax = useRef(null);

  const [blockSubscription, setBlockSubscription] = useState(null);
  const [subscription, setSubscription] = useState(null);
  const [apiKey, setApiKey] = useState('');
  const [address, setAddress] = useState('');
  const [lastTx, setLastTx] = useState();
  const [lastBlock, setLastBlock] = useState();
  const [txHistory, setTxHistory] = useState([]);

  const [customPercent, setCustomPercent] = useState();
  const [showNum, setShowNum] = useState(10);

  const isNotSameNonce = (tx) => {
    if (!tx) {
      return false;
    }

    if (!lastTx) {
      return true;
    }

    return !(tx.from === lastTx.from && tx.nonce === lastTx.nonce);
  };

  useEffect(() => {
    // replace same nonce
    setTxHistory(
      (prev) => prev?.filter(isNotSameNonce).concat(lastTx)
    );
  }, [lastTx]);

  useEffect(() => {
    if (txHistory.length > TX_LIMIT) {
      setTxHistory(
        (prev) => prev.slice(-1 * showNum)
      );
    }
  }, [txHistory]);

  const subBlock = () => {
    const web3 = createAlchemyWeb3(`wss://eth-mainnet.alchemyapi.io/v2/${apiKey}`);
    const newBlockSubscription = web3.eth.subscribe('newBlockHeaders', async (err, result) => {
      // use block hash to find transaction
      if (!err) {
        const blockDetail = await web3.eth.getBlock(result.hash);

        setLastBlock(blockDetail);

        const isNotInBlockDetail = (tx) => !blockDetail.transactions.includes(tx?.hash);

        // update tx History
        setTxHistory((txlist) => txlist.filter(isNotInBlockDetail));
      }
    });

    setBlockSubscription(newBlockSubscription);
  };

  const subscribe = async () => {
    // console.log('g1')
    if (!apiKey) {
      return;
    }

    const web3 = createAlchemyWeb3(`wss://eth-mainnet.alchemyapi.io/v2/${apiKey}`);

    // subscribe logic
    setLastTx();
    setTxHistory([]);

    // subBlock
    subBlock();

    const subCallback = (err, result) => {
      if (!err) {
        const tx = {
          from: result.from,
          hash: result.hash,
          nonce: result.nonce,
          gas: Number(result.gas),
          gasPrice: toGwei(result.gasPrice),
          maxFeePerGas: toGwei(result.maxFeePerGas),
          maxPriorityFeePerGas: toGwei(result.maxPriorityFeePerGas),
          timestamp: (new Date()).toLocaleTimeString('en-US'),
        };

        if (tx.maxPriorityFeePerGas) {
          setLastTx(tx);
        }
      }
    };

    // var blockSubscription  = web3.eth.subscribe("newBlockHeaders")
    let pendingTxSubscription = null;

    if (!address) {
      // for blank
      pendingTxSubscription = web3.eth.subscribe(
        'alchemy_fullPendingTransactions',
        subCallback
      );
    } else {
      pendingTxSubscription = web3.eth.subscribe(
        'alchemy_filteredFullPendingTransactions',
        { address },
        subCallback
      );
    }

    setSubscription(pendingTxSubscription);
  };

  const unSubscribe = () => {
    if (subscription) {
      subscription.unsubscribe((error, success) => {
        if (success) {
          console.log('MemPool Successfully unsubscribed!');
          setSubscription(null);
        }
      });
    }

    if (blockSubscription) {
      blockSubscription.unsubscribe((error, success) => {
        if (success) {
          console.log('Block Successfully unsubscribed!');
          setBlockSubscription(null);
        }
      });
    }
  };

  const handleSubscribe = (event) => {
    event.preventDefault();

    unSubscribe();
    subscribe();
  };

  const handleUnsubcribe = (event) => {
    event.preventDefault();

    unSubscribe();
  };

  const compareGas = (a, b) => b.maxPriorityFeePerGas - a.maxPriorityFeePerGas;

  // const scroll = (to) => {
  //   console.log(parallax.current);
  //   if (parallax.current) {
  //     parallax.current.scrollTo(to);
  //   }
  // };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Heading mb={6} size="3xl">
          Etheruem Gas Viewer
        </Heading>
        <Subscription
          apiKey={apiKey}
          address={address}
          setApiKey={setApiKey}
          setAddress={setAddress}
          handleSubscribe={handleSubscribe}
          handleUnsubcribe={handleUnsubcribe}
        />
        {/* Parallax */}
        <Box justifyContent="center">
          <StatisticPanel
            customPercent={customPercent}
            showNum={showNum}
            setCustomPercent={setCustomPercent}
            setShowNum={setShowNum}
            txHistory={txHistory}
            lastBlock={lastBlock}
          />
          <ListView
            txHistory={txHistory}
            compareGas={compareGas}
            showNum={showNum}
          />
          {/* <Parallax pages={2} horizontal ref={parallax} >
            <ParallaxLayer
              onClick={()=>scroll(1)}
              offset={0}
              speed={5}
              style={{ display: 'flex', justifyContent: 'center' }}>
                <ListView />
            </ParallaxLayer>
            <ParallaxLayer
              onClick={()=>scroll(0)}
              offset={1}
              sped={5}
              style={{ display: 'flex', justifyContent: 'center' }}>
                <GraphView />
            </ParallaxLayer>
          </Parallax> */}
        </Box>
      </main>
    </div>
  );
}
